Changes to Settings file
Allow the settings script file to be found either in current directory, or .SuperAttract directory

Download the settings script to /tmp when updating, to allow the upgrade to complete.

diff --git a/.SuperAttract/SuperAttract_MCP b/.SuperAttract/SuperAttract_MCP
--- a/.SuperAttract/SuperAttract_MCP
+++ b/.SuperAttract/SuperAttract_MCP
@@ -29,13 +29,20 @@
 # Thanks for the contributions and support:
 # kaloun34, redsteakraw, RetroDriven, LamerDeluxe, InquisitiveCoder, Sigismond
 
-trap 'MCP_cleanup' EXIT TERM
-
 # ======== GLOBAL VARIABLES =========
 declare -g misterpath="/media/fat"
 declare -g misterscripts="${misterpath}/Scripts"
 declare -g mrsampath="${misterscripts}/.SuperAttract"
-source ${mrsampath}/SuperAttractSystem.ini
+if [ -s SuperAttractSystem.ini ]; then
+	source SuperAttractSystem.ini
+elif [ -s ${mrsampath}/SuperAttractSystem.ini ]; then
+	source ${mrsampath}/SuperAttractSystem.ini
+else
+	echo "Error! SuperAttractSystem.ini not found!"
+	exit
+fi
+
+trap 'MCP_cleanup' EXIT TERM
 
 #======== FUNCTIONS ========
 function MCP_CoreName_Change() {
diff --git a/.SuperAttract/SuperAttract_tty2oled b/.SuperAttract/SuperAttract_tty2oled
--- a/.SuperAttract/SuperAttract_tty2oled
+++ b/.SuperAttract/SuperAttract_tty2oled
@@ -60,13 +60,21 @@
 # Thanks for the contributions and support:
 # kaloun34, redsteakraw, RetroDriven, LamerDeluxe, InquisitiveCoder, Sigismond
 
-trap 'rc=$?;[ ${rc} = 0 ] && exit;TTY_exit' EXIT TERM
-
 # ======== GLOBAL VARIABLES =========
 declare -g misterpath="/media/fat"
 declare -g misterscripts="${misterpath}/Scripts"
 declare -g mrsampath="${misterscripts}/.SuperAttract"
-source ${mrsampath}/SuperAttractSystem.ini
+if [ -s SuperAttractSystem.ini ]; then
+	source SuperAttractSystem.ini
+elif [ -s ${mrsampath}/SuperAttractSystem.ini ]; then
+	source ${mrsampath}/SuperAttractSystem.ini
+else
+	echo "Error! SuperAttractSystem.ini not found!"
+	exit
+fi
+
+trap 'rc=$?;[ ${rc} = 0 ] && exit;TTY_exit' EXIT TERM
+
 startup_tasks
 
 # ======== FUNCTIONS ========
