Update MiSTer_SAM_init

diff --git a/.MiSTer_SAM/MiSTer_SAM_init b/.MiSTer_SAM/MiSTer_SAM_init
--- a/.MiSTer_SAM/MiSTer_SAM_init
+++ b/.MiSTer_SAM/MiSTer_SAM_init
@@ -15,32 +15,56 @@ declare -g tmpfile="/tmp/.SAM_List/tmpfile"
 declare -g tmpfile2="/tmp/.SAM_List/tmpfile2"
 declare -g saminit_log="/tmp/saminit.log"
 declare -gl kids_safe
+
+#========= PARSE INI =========
+# Read INI, Check for mount point presence
+while ! test -d /media/fat/
+do
+	sleep 1
+	count=`expr $count + 1`
+	if test $count -eq 30; then
+		echo " Mount timed out!"
+      		exit 1
+ 		fi
+done
+
+if [ -f "${misterpath}/Scripts/MiSTer_SAM.ini" ]; then
+	source "${misterpath}/Scripts/MiSTer_SAM.ini"
+	IFS=',' read -ra corelist <<< "${corelist}"
+	IFS=',' read -ra corelistall <<< "${corelistall}"
+	grep "^[^#;]" < "${misterpath}/Scripts/MiSTer_SAM.ini" | grep "pathfilter=" | cut -f1 -d"=" | while IFS= read -r var; do
+		declare -g "${var}"="${!var%/}"
+	done
+fi
+
+#========= VARS CHANGED BY INI =========
 # Core to path mappings
 declare -gA PATHFILTER=(
-	["amiga"]="${amigapathfilter}"
-	["ao486"]="${ao486pathfilter}"
-	["arcade"]="${arcadepathfilter}"
-	["atari2600"]="${atari2600pathfilter}"
-	["atari5200"]="${atari5200pathfilter}"
-	["atari7800"]="${atari7800pathfilter}"
-	["atarilynx"]="${atarilynxpathfilter}"				  
-	["c64"]="${c64pathfilter}"
-	["fds"]="${fdspathfilter}"
-	["gb"]="${gbpathfilter}"
-	["gbc"]="${gbcpathfilter}"
-	["gba"]="${gbapathfilter}"
-	["genesis"]="${genesispathfilter}"
-	["gg"]="${ggpathfilter}"
-	["megacd"]="${megacdpathfilter}"
-	["neogeo"]="${neogeopathfilter}"
-	["nes"]="${nespathfilter}"
-	["s32x"]="${s32xpathfilter}"
-	["sms"]="${smspathfilter}"
-	["snes"]="${snespathfilter}"
-	["tgfx16"]="${tgfx16pathfilter}"
-	["tgfx16cd"]="${tgfx16cdpathfilter}"
-	["psx"]="${psxpathfilter}"
+["amiga"]="${amigapathfilter}"
+["ao486"]="${ao486pathfilter}"
+["arcade"]="${arcadepathfilter}"
+["atari2600"]="${atari2600pathfilter}"
+["atari5200"]="${atari5200pathfilter}"
+["atari7800"]="${atari7800pathfilter}"
+["atarilynx"]="${atarilynxpathfilter}"				  
+["c64"]="${c64pathfilter}"
+["fds"]="${fdspathfilter}"
+["gb"]="${gbpathfilter}"
+["gbc"]="${gbcpathfilter}"
+["gba"]="${gbapathfilter}"
+["genesis"]="${genesispathfilter}"
+["gg"]="${ggpathfilter}"
+["megacd"]="${megacdpathfilter}"
+["neogeo"]="${neogeopathfilter}"
+["nes"]="${nespathfilter}"
+["s32x"]="${s32xpathfilter}"
+["sms"]="${smspathfilter}"
+["snes"]="${snespathfilter}"
+["tgfx16"]="${tgfx16pathfilter}"
+["tgfx16cd"]="${tgfx16cdpathfilter}"
+["psx"]="${psxpathfilter}"
 )
+
 
 #======== DEBUG VARIABLES ========
 samquiet="Yes"
@@ -62,23 +86,6 @@ killall -q -9 MiSTer_SAM_keyboard.py 2>/dev/null
 kill -9 $(ps -o pid,args | grep "inotifywait" | grep "SAM_Joy_Change" | { read -r PID COMMAND; echo $PID; }) 2>/dev/null
 echo " Done!"
 
-#========= PARSE INI =========
-# Read INI, Check for mount point presence
-while ! test -d /media/fat/
-do
-	sleep 1
-	count=`expr $count + 1`
-	if test $count -eq 30; then
-		echo " Mount timed out!"
-      		exit 1
- 		fi
-done
-
-if [ -f "${misterpath}/Scripts/MiSTer_SAM.ini" ]; then
-	source "${misterpath}/Scripts/MiSTer_SAM.ini"
-	IFS=',' read -ra corelist <<< "${corelist}"
-	IFS=',' read -ra corelistall <<< "${corelistall}"
-fi
 
 #========= PREP =========
 mkdir -p "${gamelistpathtmp}"
@@ -113,8 +120,10 @@ function filter_list() { # args ${nextcore}
 		
 	# Check path filter
 	if [ -n "${PATHFILTER[${1}]}" ]; then 
-		echo "Found path filter for ${1} core: ${PATHFILTER[${1}]}."
+		echo "Found path filter for ${1} core: ${PATHFILTER[${1}]}." >> ${saminit_log}
 		fgrep "${PATHFILTER[${1}]}" "${gamelistpathtmp}/${1}_gamelist.txt"  > "${tmpfile}" && cp -f "${tmpfile}" "${gamelistpathtmp}/${1}_gamelist.txt"
+	else
+		echo "No path filter found for ${1} - ${PATHFILTER[${1}]}" >> ${saminit_log}
 	fi
 	
 	if [ -n "${arcadeorient}" ] && [[ "${1}" == "arcade" ]]; then
@@ -133,13 +142,13 @@ function filter_list() { # args ${nextcore}
 	#Check exclusion or kids safe white lists
 	#First check for category exclusion
 	if [ -f "${gamelistpath}/${1}_gamelist_exclude.txt" ]; then
-		echo "Found category excludelist for core ${1}. Stripping out unwanted games now."
+		echo "Found category excludelist for core ${1}. Stripping out unwanted games now." >> ${saminit_log}
 		# Process full file paths from gamelist_exclude
 		awk 'FNR==NR{a[$0];next} !($0 in a)' "${gamelistpath}/${1}_gamelist_exclude.txt" "${gamelistpathtmp}/${1}_gamelist.txt" > "${tmpfilefilter}" 
 		mv "${tmpfilefilter}" "${gamelistpathtmp}/${1}_gamelist.txt"
 	fi
 	if [ -f "${gamelistpath}/${1}_excludelist.txt" ]; then
-		echo "Found excludelist for core ${1}. Stripping out unwanted games now."
+		echo "Found excludelist for core ${1}. Stripping out unwanted games now." >> ${saminit_log}
 		# Process file names without extensions from excludelist
 		awk "BEGIN { while (getline < \"${gamelistpath}/${1}_excludelist.txt\") { a[\$0] = 1 } close(\"${gamelistpath}/${1}_excludelist.txt\"); } \
 		{ gamelistfile = \$0; sub(/\\.[^.]*\$/, \"\", gamelistfile); sub(/^.*\\//, \"\", gamelistfile); if (!(gamelistfile in a)) print }" \
@@ -156,13 +165,13 @@ function filter_list() { # args ${nextcore}
 				fgrep -f "${mrsampath}/SAM_Rated/${1}_rated.txt" "${gamelistpathtmp}/${1}_gamelist.txt" | awk -F "/" '{split($NF,a," \\("); if (!seen[a[1]]++) print $0}' > "${tmpfilefilter}"
 			fi
 			if [ -s "${tmpfilefilter}" ]; then 
-				samdebug "$(wc -l <"${tmpfilefilter}") games after kids safe filter applied."
+				samdebug "$(wc -l <"${tmpfilefilter}") games after kids safe filter applied." >> ${saminit_log}
 				cp -f "${tmpfilefilter}" "${gamelistpathtmp}/${1}_gamelist.txt"
 			else
 				delete_from_corelist "${1}"
 				delete_from_corelist "${1}" tmp
-				echo "${1} kids safe filter produced no results and will be disabled."
-				echo "List of cores is now: ${corelist[*]}"
+				echo "${1} kids safe filter produced no results and will be disabled." >> ${saminit_log}
+				echo "List of cores is now: ${corelist[*]}" >> ${saminit_log}
 				return 1
 			fi
 	fi
@@ -186,7 +195,7 @@ function filter_list() { # args ${nextcore}
 		if [ -s "${tmpfilefilter}" ]; then 
 			cp -f "${tmpfilefilter}" "${gamelistpathtmp}/${1}_gamelist.txt"
 		else
-			samdebug "Blacklist filter failed" 
+			samdebug "Blacklist filter failed" >> ${saminit_log}
 		fi
 	fi
 }
@@ -219,7 +228,7 @@ function gl_filter() {
 	if [ "${kids_safe}" == "yes" ]; then
 		echo "Kids Safe Mode active."
 		if [ ! -f "${mrsampath}"/SAM_Rated/amiga_rated.txt ]; then
-			echo "No kids safe rating lists found."
+			echo "No kids safe rating lists found." >> ${saminit_log}
 			return 1
 		fi
 		#Set corelist to only include cores with rated lists
@@ -241,7 +250,7 @@ function gl_filter() {
 	fi
 
 	if [ $? -gt 1 ]; then
-		echo "Couldn't find Arcade games. Please run update_all.sh first or add some Arcade games manually."
+		echo "Couldn't find Arcade games. Please run update_all.sh first or add some Arcade games manually." >> ${saminit_log}
 		sleep 5
 		exit
 	fi
@@ -254,7 +263,7 @@ function gl_filter() {
 
 	for g in "${glondisk[@]}"; do 
 		if [ "${g}" == "amiga" ] || [ "${g}" == "ao486" ]; then
-			echo "Amiga and AO486 will be processed in main script"
+			echo "Amiga and AO486 will be processed in main script" 
 			continue
 		fi
 		if [ ! -s "${gamelistpathtmp}/${g}_gamelist.txt" ]; then	
